# Generated by Django 5.2.16 on 2026-07-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('agent', 'Agent'), ('customer', 'Customer')], default='agent', max_length=20),
        ),
    ]
